replicaCount: 1

image:
  repository: 989200477899.dkr.ecr.us-east-2.amazonaws.com/dev-dealengine-ecr-repo
  digest: sha256:d3d5f8bc472bf1ace99be5fcbffce4b7e1778cc4ebd111435a17b03851493434

existingSecret: backend-runtime

rdsCa:
  enabled: true

tolerations:
  - key: workload
    operator: Equal
    value: shared
    effect: NoSchedule

httpRoute:
  enabled: true
  hostname: api.alb-dev-dealengine.saul-tzakum.tech
  parentRef:
    name: gateway-dev
    namespace: gateway-system
    sectionName: https