replicaCount: 1

image:
  repository: 989200477899.dkr.ecr.us-east-2.amazonaws.com/dev-dealengine-ecr-repo
  digest: sha256:c214109f16b199b6cac916bbb5b3d0e543dfa231929b7c2360f5be6e697afb63

existingSecret: backend-runtime

tolerations:
  - key: workload
    operator: Equal
    value: shared
    effect: NoSchedule

httpRoute:
  enabled: true
  hostname: api.alb-dev-dealengine.saul-tzakum.tech
  parentRef:
    name: gateway-dev
    namespace: gateway-system
    sectionName: https